"b1g_genre_sm": <?php echo(json_encode($genre)); ?>,
"b1g_geom_type_sm":<?php echo(json_encode($b1gGeomType)); ?>,
"b1g_centroid_ss": <?php echo(json_encode($centroid)); ?>,
"b1g_geonames_sm": <?php echo(json_encode($relation)); ?>,
"b1g_image_ss": <?php echo(json_encode($image)); ?>,
"b1g_collection_sm": <?php echo(json_encode($code)); ?>,